// suggested quotes from https://type.fit/api/quotes
export const GET_SUGGESTED_QUOTES_REQUEST = "GET_SUGGESTED_QUOTES_REQUEST";
export const GET_SUGGESTED_QUOTES_SUCCESS = "GET_SUGGESTED_QUOTES_SUCCESS";
export const GET_SUGGESTED_QUOTES_FAIL = "GET_SUGGESTED_QUOTES_FAIL";

// add quote
export const ADD_QUOTE_REQUEST = "ADD_QUOTE_REQUEST";
export const ADD_QUOTE_SUCCESS = "ADD_QUOTE_SUCCESS";
export const ADD_QUOTE_FAIL = "ADD_QUOTE_FAIL";