// suggested quotes from https://type.fit/api/quotes
export const GET_SUGGESTED_QUOTES_REQUEST = "GET_SUGGESTED_QUOTES_REQUEST";
export const GET_SUGGESTED_QUOTES_SUCCESS = "GET_SUGGESTED_QUOTES_SUCCESS";
export const GET_SUGGESTED_QUOTES_FAIL = "GET_SUGGESTED_QUOTES_FAIL";

// add quote
export const ADD_QUOTE_REQUEST = "ADD_QUOTE_REQUEST";
export const ADD_QUOTE_SUCCESS = "ADD_QUOTE_SUCCESS";
export const ADD_QUOTE_FAIL = "ADD_QUOTE_FAIL";

// get quotes
export const GET_QUOTES_REQUEST = "GET_QUOTES_REQUEST";
export const GET_QUOTES_SUCCESS = "GET_QUOTES_SUCCESS";
export const GET_QUOTES_FAIL = "GET_QUOTES_FAIL";

// search/filter quotes
export const SEARCH_QUOTE = "SEARCH_QUOTE";

// auth
export const CREATE_USER_REQUEST = "CREATE_USER_REQUEST";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const CREATE_USER_FAIL = "CREATE_USER_FAIL";   

export const LOGOUT_USER_REQUEST = "LOGOUT_USER_REQUEST";
export const LOGOUT_USER_SUCCESS = "LOGOUT_USER_SUCCESS";
export const LOGOUT_USER_FAIL = "LOGOUT_USER_FAIL";